//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gallery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Author.
    /// </summary>
    //  *** Start programmer edit section *** (Author CustomAttributes)

    //  *** End programmer edit section *** (Author CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuthorE", new string[] {
            "Name as \'Name\'",
            "Birthday as \'Birthday\'"})]
    [View("AuthorL", new string[] {
            "Name as \'Name\'",
            "Birthday as \'Birthday\'"})]
    public class Author : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fBirthday;
        
        //  *** Start programmer edit section *** (Author CustomMembers)

        //  *** End programmer edit section *** (Author CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Author.Name CustomAttributes)

        //  *** End programmer edit section *** (Author.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Author.Name Get start)

                //  *** End programmer edit section *** (Author.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Author.Name Get end)

                //  *** End programmer edit section *** (Author.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Author.Name Set start)

                //  *** End programmer edit section *** (Author.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Author.Name Set end)

                //  *** End programmer edit section *** (Author.Name Set end)
            }
        }
        
        /// <summary>
        /// Birthday.
        /// </summary>
        //  *** Start programmer edit section *** (Author.Birthday CustomAttributes)

        //  *** End programmer edit section *** (Author.Birthday CustomAttributes)
        public virtual System.DateTime Birthday
        {
            get
            {
                //  *** Start programmer edit section *** (Author.Birthday Get start)

                //  *** End programmer edit section *** (Author.Birthday Get start)
                System.DateTime result = this.fBirthday;
                //  *** Start programmer edit section *** (Author.Birthday Get end)

                //  *** End programmer edit section *** (Author.Birthday Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Author.Birthday Set start)

                //  *** End programmer edit section *** (Author.Birthday Set start)
                this.fBirthday = value;
                //  *** Start programmer edit section *** (Author.Birthday Set end)

                //  *** End programmer edit section *** (Author.Birthday Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuthorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuthorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuthorE", typeof(IIS.Gallery.Author));
                }
            }
            
            /// <summary>
            /// "AuthorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuthorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuthorL", typeof(IIS.Gallery.Author));
                }
            }
        }
    }
}
