//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gallery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass1.
    /// </summary>
    //  *** Start programmer edit section *** (NewClass1 CustomAttributes)

    //  *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {
        
        private int fattr1;
        
        //  *** Start programmer edit section *** (NewClass1 CustomMembers)

        //  *** End programmer edit section *** (NewClass1 CustomMembers)

        
        /// <summary>
        /// attr1.
        /// </summary>
        //  *** Start programmer edit section *** (NewClass1.attr1 CustomAttributes)

        //  *** End programmer edit section *** (NewClass1.attr1 CustomAttributes)
        public virtual int attr1
        {
            get
            {
                //  *** Start programmer edit section *** (NewClass1.attr1 Get start)

                //  *** End programmer edit section *** (NewClass1.attr1 Get start)
                int result = this.fattr1;
                //  *** Start programmer edit section *** (NewClass1.attr1 Get end)

                //  *** End programmer edit section *** (NewClass1.attr1 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (NewClass1.attr1 Set start)

                //  *** End programmer edit section *** (NewClass1.attr1 Set start)
                this.fattr1 = value;
                //  *** Start programmer edit section *** (NewClass1.attr1 Set end)

                //  *** End programmer edit section *** (NewClass1.attr1 Set end)
            }
        }
    }
}
