//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gallery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Picture.
    /// </summary>
    //  *** Start programmer edit section *** (Picture CustomAttributes)

    //  *** End programmer edit section *** (Picture CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PictureE", new string[] {
            "Name as \'Name\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'"})]
    [View("PictureL", new string[] {
            "Name as \'Name\'",
            "Author.Name as \'Name\'"})]
    public class Picture : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Gallery.Author fAuthor;
        
        //  *** Start programmer edit section *** (Picture CustomMembers)

        //  *** End programmer edit section *** (Picture CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Picture.Name CustomAttributes)

        //  *** End programmer edit section *** (Picture.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Picture.Name Get start)

                //  *** End programmer edit section *** (Picture.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Picture.Name Get end)

                //  *** End programmer edit section *** (Picture.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Picture.Name Set start)

                //  *** End programmer edit section *** (Picture.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Picture.Name Set end)

                //  *** End programmer edit section *** (Picture.Name Set end)
            }
        }
        
        /// <summary>
        /// Picture.
        /// </summary>
        //  *** Start programmer edit section *** (Picture.Author CustomAttributes)

        //  *** End programmer edit section *** (Picture.Author CustomAttributes)
        public virtual IIS.Gallery.Author Author
        {
            get
            {
                //  *** Start programmer edit section *** (Picture.Author Get start)

                //  *** End programmer edit section *** (Picture.Author Get start)
                IIS.Gallery.Author result = this.fAuthor;
                //  *** Start programmer edit section *** (Picture.Author Get end)

                //  *** End programmer edit section *** (Picture.Author Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Picture.Author Set start)

                //  *** End programmer edit section *** (Picture.Author Set start)
                this.fAuthor = value;
                //  *** Start programmer edit section *** (Picture.Author Set end)

                //  *** End programmer edit section *** (Picture.Author Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PictureE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PictureE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PictureE", typeof(IIS.Gallery.Picture));
                }
            }
            
            /// <summary>
            /// "PictureL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PictureL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PictureL", typeof(IIS.Gallery.Picture));
                }
            }
        }
    }
}
